### ISSUE TITLE
Shortening the archive path

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco-postprocess#29]
Should we create a tiny URL to alleviate the [long path problem](https://github.com/numbbo/coco/issues/2268)?

**Comment by nikohansen** [comment]
FTR, 260 chars seems to be a limit under windows.

- The Windows cache location has an offset of `len(username) + 43`, see [here](https://github.com/numbbo/coco/issues/2268)
- `len('data-archives\numbbo.github.io\data-archive\data-archive') == 55`
- a typical long-ish path name within the archive is 25 chars
- a long zip filename is 30 chars
- `len('.extracted_CMA-ESPLUSSEL_auger_noiseless/CMA-ESPLUSSEL/bbobdata-cmaesplussel1e4/data_f10/bbobexp_f10_DIM10.dat') == 110`

The [current error](https://github.com/numbbo/coco/issues/2268) is raised preemptively in the coco code, not by the OS.

Changing the format to `.zip` and not extracting the file while reading in would solve this problem too.

**Comment by nikohansen** [comment]
The latest commit shortens the local path for the official data archive by 50 chars, namely from 

`.../data-archives/numbbo.github.io/data-archive/data-archive/...` 
to 
`.../das/da/...`

**Comment by brockho** [comment]
> The latest commit shortens the local path for the official data archive by 50 chars, namely from
> 
> `.../data-archives/numbbo.github.io/data-archive/data-archive/...` to `.../das/da/...`

Thanks, @nikohansen, this solved the problem for me when using `cocopp` "normally" as a user. For the archive creation, I still had to remove the `list_local_archives.txt` file  again - as explained [here](https://github.com/numbbo/coco-postprocess/issues/22).

**Comment by nikohansen** [comment]
> For the archive creation, I still had to remove the `list_local_archives.txt` file again - as explained [here](https://github.com/numbbo/coco-postprocess/issues/22).

I had change the `ValueError` to a warning before the changes for the path length, which means the error message should have been different. For me, `create` works without complaints, so I could not reproduce the problem in my configuration.
